(function(){
  const clone=value=>JSON.parse(JSON.stringify(value));
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>`cardapio-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
  const defaultMenu=()=>({id:uid(),name:'Cardápio Vinicinho Doces',logo:'assets/logo-vinicinho-transparente.png',pix:'17 98846-1563',qr:'17 98846-1563',theme:{brown:'#64260f',orange:'#dc7809',cream:'#fff4df'},pages:[
    {name:'Frente',sections:[
      {title:'CONES TRUFADOS',price:'R$ 10,00 un',items:[{name:'Ferrero Rocher',price:'R$ 11,00'},{name:'Kinder Ovo',price:''},{name:'Oreo',price:''},{name:'Brigadeiro',price:''}]},
      {title:'BOLOS DE POTE',price:'R$ 10,00',items:[{name:'Limão',price:''},{name:'Brigoninho',price:''},{name:'Brigoninho com morango',price:''},{name:'Ninho com morango',price:''},{name:'Abacaxi',price:''},{name:'Abacaxi com doce de leite',price:''},{name:'Ninho com Nutella',price:'R$ 12,00'}]},
      {title:'PÃES DE MEL',price:'R$ 10,00',items:[{name:'Ninho',price:''},{name:'Doce de leite',price:''},{name:'Brigadeiro de café',price:''}]},
      {title:'BALA DE NINHO',price:'R$ 5,00',items:[]}
    ]},
    {name:'Verso',sections:[
      {title:'CONES',price:'',items:[{name:'1 un',price:'R$ 10,00'},{name:'2 un',price:'R$ 18,00'},{name:'3 un',price:'R$ 25,00'}]},
      {title:'BOLOS DE POTE',price:'',items:[{name:'Bolo de pote',price:'R$ 10,00'},{name:'Ninho com Nutella',price:'R$ 12,00'}]}
    ],showPix:true}
  ]});
  const blankMenu=()=>({id:uid(),name:'Novo cardápio',logo:'assets/logo-vinicinho-sem-fundo.png',pix:'',qr:'',theme:{brown:'#64260f',orange:'#dc7809',cream:'#fff4df'},pages:[{name:'Frente',sections:[]},{name:'Verso',sections:[],showPix:true}]});
  let api,menus,current,pageIndex=0,root;
  function input(label,name,value,type='text'){return `<label>${label}<input data-field="${name}" type="${type}" value="${esc(value)}"></label>`}
  function preview(){const page=current.pages[pageIndex];return `<div class="menu-sheet" style="--menu-brown:${esc(current.theme.brown)};--menu-orange:${esc(current.theme.orange)};--menu-cream:${esc(current.theme.cream)}"><div class="menu-frame"><img class="menu-logo" src="${esc(current.logo)}" alt="Logo"><div class="menu-sections">${page.sections.map(s=>`<section class="menu-section"><header><b>${esc(s.title||'TÍTULO')}</b>${s.price?`<strong>${esc(s.price)}</strong>`:''}</header>${s.items.length?`<div>${s.items.map(i=>`<p><span>${esc(i.name||'Produto')}</span>${i.price?`<strong>${esc(i.price)}</strong>`:''}</p>`).join('')}</div>`:''}</section>`).join('')}${page.showPix?`<aside class="menu-pix"><b>CHAVE PIX</b><strong>${esc(current.pix||'Adicione a chave PIX')}</strong></aside><div class="menu-qr"></div>`:''}</div></div></div>`}
  function sectionEditor(){const page=current.pages[pageIndex];return page.sections.map((s,si)=>`<article class="menu-edit-section" data-section="${si}"><div class="menu-section-fields">${input('Título','title',s.title)}${input('Valor no título','price',s.price)}<button data-cmd="remove-section" title="Excluir seção">×</button></div><div class="menu-edit-items">${s.items.map((i,ii)=>`<div class="menu-edit-item" data-item="${ii}">${input('Nome do produto','name',i.name)}${input('Valor ao lado','price',i.price)}<button data-cmd="remove-item" title="Excluir produto">×</button></div>`).join('')}</div><button class="menu-small" data-cmd="add-item">+ Produto</button></article>`).join('')}
  function render(){root.innerHTML=`<div class="menu-editor"><header class="menu-editor-top"><div><h2>Editor de cardápios</h2><small>Crie, edite a frente e o verso e salve em PDF.</small></div><div><button data-cmd="close">Fechar</button><button data-cmd="save">Salvar</button><button class="menu-pdf-btn" data-cmd="pdf">Salvar em PDF</button></div></header><div class="menu-editor-body"><aside class="menu-tools"><label>Cardápio<select data-menu-select>${menus.map(m=>`<option value="${m.id}" ${m.id===current.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label><div class="menu-tool-row"><button data-cmd="new">+ Do zero</button><button data-cmd="duplicate">Duplicar</button><button data-cmd="delete">Excluir</button></div>${input('Nome do cardápio','menuName',current.name)}<div class="menu-tabs"><button class="${pageIndex===0?'active':''}" data-page="0">Frente</button><button class="${pageIndex===1?'active':''}" data-page="1">Verso</button></div><h3>Identidade visual</h3><label>Logo<input data-logo type="file" accept="image/*"></label><button class="menu-small" data-cmd="remove-logo">Remover logo</button><div class="menu-colors">${input('Marrom','brown',current.theme.brown,'color')}${input('Laranja','orange',current.theme.orange,'color')}${input('Fundo','cream',current.theme.cream,'color')}</div>${pageIndex===1?`<h3>Pagamento</h3>${input('Chave PIX','pix',current.pix)}${input('Conteúdo do QR Code','qr',current.qr)}<label class="menu-check"><input data-show-pix type="checkbox" ${current.pages[1].showPix?'checked':''}> Mostrar PIX e QR Code</label>`:''}<h3>Conteúdo da ${pageIndex?'verso':'frente'}</h3><div class="menu-section-editor">${sectionEditor()}</div><button class="menu-add-section" data-cmd="add-section">+ Adicionar título / seção</button></aside><main class="menu-preview-wrap"><div class="menu-preview-toolbar"><span>Pré-visualização A4 — ${pageIndex?'Verso':'Frente'}</span><small>O PDF terá uma página para cada lado.</small></div><div class="menu-preview">${preview()}</div></main></div></div>`;bind();renderQr()}
  function updateFromField(el){const field=el.dataset.field;if(field==='menuName')current.name=el.value;else if(['brown','orange','cream'].includes(field))current.theme[field]=el.value;else if(field==='pix'||field==='qr')current[field]=el.value;else{const section=el.closest('[data-section]'),item=el.closest('[data-item]');if(section){const target=item?current.pages[pageIndex].sections[+section.dataset.section].items[+item.dataset.item]:current.pages[pageIndex].sections[+section.dataset.section];target[field]=el.value}}render()}
  function bind(){root.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>updateFromField(el));root.querySelector('[data-menu-select]').onchange=e=>{current=menus.find(m=>m.id===e.target.value);pageIndex=0;render()};root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{pageIndex=+b.dataset.page;render()});root.querySelector('[data-show-pix]')?.addEventListener('change',e=>{current.pages[1].showPix=e.target.checked;render()});root.querySelector('[data-logo]').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{current.logo=reader.result;render()};reader.readAsDataURL(file)};root.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>command(b.dataset.cmd,b));}
  function command(cmd,button){const section=button.closest('[data-section]'),item=button.closest('[data-item]'),si=section?+section.dataset.section:-1,ii=item?+item.dataset.item:-1,page=current.pages[pageIndex];if(cmd==='close')return root.remove();if(cmd==='save'){api.save(clone(menus));return toast('Cardápio salvo no Firebase')};if(cmd==='new'){current=blankMenu();menus.push(current);pageIndex=0}else if(cmd==='duplicate'){const copy=clone(current);copy.id=uid();copy.name+=' — cópia';menus.push(copy);current=copy}else if(cmd==='delete'){if(menus.length===1)return toast('Mantenha ao menos um cardápio');menus=menus.filter(m=>m.id!==current.id);current=menus[0];pageIndex=0}else if(cmd==='remove-logo')current.logo='';else if(cmd==='add-section')page.sections.push({title:'NOVO TÍTULO',price:'',items:[{name:'Novo produto',price:''}]});else if(cmd==='remove-section')page.sections.splice(si,1);else if(cmd==='add-item')page.sections[si].items.push({name:'Novo produto',price:''});else if(cmd==='remove-item')page.sections[si].items.splice(ii,1);else if(cmd==='pdf')return exportPdf();render()}
  function renderQr(){const box=root.querySelector('.menu-qr');if(!box||!current.qr||!window.QRCode)return;box.innerHTML='';new QRCode(box,{text:current.qr,width:112,height:112,colorDark:'#2e1208',colorLight:'#fffaf0',correctLevel:QRCode.CorrectLevel.M})}
  function toast(text){const t=document.getElementById('toast');if(t){t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}}
  async function exportPdf(){if(!window.html2canvas||!window.jspdf)return toast('Biblioteca de PDF ainda não carregou. Tente novamente.');const button=root.querySelector('[data-cmd="pdf"]');button.disabled=true;button.textContent='Gerando PDF…';try{const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'}),original=pageIndex;for(let p=0;p<2;p++){pageIndex=p;render();const sheet=root.querySelector('.menu-sheet'),canvas=await html2canvas(sheet,{scale:2,useCORS:true,backgroundColor:'#fff4df'});if(p)pdf.addPage();pdf.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,210,297)}pdf.save(`${current.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').toLowerCase()||'cardapio'}.pdf`);pageIndex=original;render();toast('PDF com frente e verso salvo')}catch(error){console.error(error);toast('Não foi possível gerar o PDF')}finally{root.querySelector('[data-cmd="pdf"]')?.removeAttribute('disabled')}}
  window.VinicinhoMenuEditor={open(options){api=options;menus=clone(options.data||[]);if(!menus.length){menus=[defaultMenu()];options.save(clone(menus))}current=menus[0];pageIndex=0;root=document.createElement('div');root.className='menu-editor-backdrop';document.body.appendChild(root);render()}};
})();
