const pages = {
  Vendas: `
    <section class="page-shell"><div class="page-head"><div><h1>Vendas</h1><p>Registre pedidos, pagamentos e saldos em aberto</p></div><div class="page-head-actions"><button class="outline-btn" data-action="Nova pré-venda">+ Pedido pré-venda</button><button class="primary-btn" data-action="Nova venda">+ Nova venda</button></div></div>
    <div class="page-stats five">${stat('orange','Vendas do mês','R$ 32,00')}${stat('green','Recebido','R$ 10,00')}${stat('yellow','Pendente','R$ 22,00')}${stat('deep','Ticket médio','R$ 16,00')}${stat('blue','Total pré-venda','R$ 0,00')}</div>
    <div class="panel"><h2>Lista de vendas</h2><div class="search-row"><input class="search-box" placeholder="Buscar cliente ou produto..."><button class="outline-btn" data-action="Filtro de período">Filtrar período</button></div>
    ${table(['Data','Cliente','Produtos','Total','Recebido','Saldo','Situação'],[['19/08/2026','Guilherme','3 × Bala de Ninho','R$ 15,00','R$ 10,00','R$ 5,00','<span class="status partial">Parcial</span>'],['19/08/2026','Priscila','2 × Mousse','R$ 17,00','R$ 0,00','R$ 17,00','<span class="status unpaid">Não pago</span>']])}
    <div class="note-box"><strong>Como funciona</strong>Ao salvar uma venda com saldo pendente, o sistema cria automaticamente uma conta a receber.</div></div>
    <div class="panel presale-panel"><div class="card-title"><div><h2>Pré-vendas agrupadas</h2><p>Pedidos organizados por previsão de chegada e ponto de venda.</p></div><span class="status partial presale-count">0 pendentes</span></div>${table(['Data','Ponto de venda','Pré-vendas','Clientes','Produtos','Total','Ações'],[])}</div></section>`,
  'Contas a Receber': `
    <section class="page-shell"><div class="page-head"><div><h1>Contas a receber</h1><p>Acompanhe cobranças, vencimentos e pagamentos parciais</p></div><button class="primary-btn" data-action="Registrar pagamento">Registrar pagamento</button></div>
    <div class="page-stats">${stat('yellow','Total a receber','R$ 22,00')}${stat('orange','Vencendo hoje','R$ 5,00')}${stat('red','Em atraso','R$ 17,00')}</div>
    <div class="panel"><h2>Pendências por cliente</h2>${table(['Cliente','Venda','Valor original','Pago','Saldo','Vencimento','Status'],[['Guilherme','#0001','R$ 15,00','R$ 10,00','R$ 5,00','19/08/2026','<span class="status partial">Parcial</span>'],['Priscila','#0002','R$ 17,00','R$ 0,00','R$ 17,00','18/08/2026','<span class="status unpaid">Não pago</span>']])}<div class="page-grid" style="margin-top:78px"><div class="panel"><h2>Próximas ações</h2><p>• Enviar lembrete para Priscila</p><p>• Confirmar saldo de Guilherme</p><p>• Baixar pagamento recebido</p></div><div class="panel"><h2>Resumo</h2><b>2 clientes com pendência</b><p class="green-text">Recebido das vendas: R$ 10,00</p><p class="red-text">Ainda a receber: R$ 22,00</p></div></div></div></section>`,
  'Contas a Pagar': `
    <section class="page-shell"><div class="page-head"><div><h1>Contas a pagar</h1><p>Acompanhe compras pendentes, vencimentos e pagamentos a fornecedores</p></div><div class="page-head-actions"><button class="outline-btn" data-action="Registrar pagamento de despesa">Registrar pagamento</button><button class="primary-btn" data-action="Nova conta a pagar">+ Nova conta a pagar</button></div></div>
    <div class="page-stats">${stat('yellow','Total a pagar','R$ 0,00')}${stat('orange','Vencendo hoje','R$ 0,00')}${stat('red','Em atraso','R$ 0,00')}</div>
    <div class="panel"><h2>Pendências por fornecedor</h2>${table(['Fornecedor','Despesa','Valor original','Pago','Saldo','Vencimento','Status'],[])}<div class="page-grid" style="margin-top:78px"><div class="panel"><h2>Próximas ações</h2><p class="green-text">• Nenhuma conta pendente.</p></div><div class="panel"><h2>Resumo</h2><b>0 fornecedores com pendência</b><p class="green-text">Total pago: R$ 0,00</p><p class="red-text">Ainda a pagar: R$ 0,00</p></div></div></div></section>`,
  Despesas: `
    <section class="page-shell"><div class="page-head"><div><h1>Despesas</h1><p>Registre compras de fornecedores e saídas do caixa</p></div><div class="page-head-actions"><button class="outline-btn" data-action="Pedido de compra das pré-vendas">Pedido das pré-vendas</button><button class="primary-btn" data-action="Nova despesa">+ Nova despesa</button></div></div><div class="page-stats">${stat('red','Despesas do mês','R$ 8,00')}${stat('green','Pagas','R$ 8,00')}${stat('yellow','A pagar','R$ 0,00')}</div>
    <div class="page-grid"><div class="panel"><h2>Lançamentos</h2>${table(['Data','Fornecedor','Categoria','Valor'],[['19/08/2026','Mercado Central','Ingredientes','R$ 8,00'],['—','Nenhuma outra despesa','—','—']])}</div><div class="side-stack"><div class="panel"><h2>Nova despesa</h2><div class="form-grid" style="grid-template-columns:120px 1fr">${field('Fornecedor','Mercado Central')}${field('Categoria','Ingredientes')}${field('Valor','R$ 8,00')}<div></div><button class="primary-btn" data-action="Despesa salva">Salvar despesa</button></div></div><div class="panel"><h2>Despesas por categoria</h2><div class="donut-big"><b>R$ 8</b></div><p style="text-align:center">Ingredientes &nbsp; <b>100%</b></p></div></div></div></section>`,
  Produtos: `
    <section class="page-shell"><div class="page-head"><div><h1>Produtos e receitas</h1><p>Cadastre produtos prontos ou produzidos por você</p></div><button class="primary-btn" data-action="Novo produto">+ Novo produto</button></div><div class="page-grid products-layout"><div class="panel product-list"><h2>Produtos cadastrados</h2>${table(['Produto','Tipo','Preço'],[['<b>Bala de Ninho</b>','Produzido','<b class="orange-text">R$ 5,00</b>'],['<b>Mousse</b>','Produzido','<b class="orange-text">R$ 8,00</b>'],['<b>Cone Ferrero</b>','Produzido','<b class="orange-text">R$ 10,00</b>'],['<b>Refrigerante lata</b>','Pronto','<b class="orange-text">R$ 6,00</b>']])}<div class="stock-mini"><div><span>Estoque do produto selecionado</span><strong class="stock-quantity">0 un.</strong><small class="stock-status">Selecione um produto</small></div><button class="outline-btn" data-action="Ajustar estoque">Ajustar estoque</button></div><div class="combo-mini"><div><span>Combos cadastrados</span><strong class="combo-summary">Nenhum combo</strong><small>Aplicados automaticamente nas vendas.</small></div><button class="outline-btn" data-action="Cadastrar combo">Cadastrar combo</button></div><div class="note-box"><strong>Tipos de produto</strong><b>Pronto</b><p>Comprado para revenda: controla custo e estoque.</p><b>Produzido</b><p>Possui receita, ingredientes e custo calculado.</p></div></div><div class="panel"><h2>Receita — Bala de Ninho</h2><div class="recipe-summary"><div><span>Preço de venda</span><strong>R$ 5,00</strong></div><div><span>Custo estimado</span><strong>R$ 2,10</strong></div><div><span>Lucro/un.</span><strong>R$ 2,90</strong></div></div><h2>Ingredientes</h2>${table(['Ingrediente','Quantidade','Custo'],[['Leite em pó','30 g','<b>R$ 0,90</b>'],['Leite condensado','40 g','<b>R$ 0,80</b>'],['Açúcar','10 g','<b>R$ 0,10</b>'],['Embalagem','1 un','<b>R$ 0,30</b>']])}<button class="primary-btn" data-action="Editar receita" style="float:right;margin-top:100px">Editar receita</button></div></div></section>`,
  Produção: `
    <section class="page-shell"><div class="page-head"><div><h1>Controle de produção</h1><p>Transforme ingredientes em produtos prontos e mantenha o estoque atualizado</p></div></div>
    <div class="page-stats four">${stat('orange','Produzido hoje','0 un.')}${stat('red','Ingredientes consumidos','0')}${stat('green','Lotes finalizados','0')}${stat('deep','Produtos acabados em estoque','0 un.')}</div>
    <div class="page-grid production-layout"><div class="panel production-form-panel"><h2>Finalizar nova produção</h2><div class="production-form"><label>Produto produzido<select class="production-product"></select></label><label>Quantidade do lote<input class="production-quantity" type="number" min="1" step="1" value="1"></label><label>Data da produção<input class="production-date" type="date"></label></div><div class="production-requirements"><p>Selecione um produto para conferir os ingredientes necessários.</p></div><button class="primary-btn production-finish" data-action="Finalizar produção">Finalizar produção</button></div><div class="panel production-history"><h2>Histórico de produções</h2>${table(['Data','Produto','Quantidade','Ingredientes consumidos','Responsável'],[])}</div></div></section>`,
  Caixa: `
    <section class="page-shell"><div class="page-head"><div><h1>Caixa</h1><p>Acompanhe caixas do negócio e suas finanças pessoais separadamente</p></div><div class="page-head-actions cash-head-actions"><select class="cash-account-select" aria-label="Caixa selecionado"></select><button class="outline-btn" data-action="Transferir entre caixas">Transferir</button><button class="outline-btn" data-action="Novo caixa">+ Novo caixa</button><button class="primary-btn" data-action="Novo lançamento de caixa">+ Novo lançamento</button></div></div>
    <div class="page-stats">${stat('green','Saldo atual','R$ 0,00')}${stat('orange','Total de entradas','R$ 0,00')}${stat('red','Total de saídas','R$ 0,00')}</div>
    <div class="panel"><div class="card-title"><h2>Movimentações do caixa</h2><button class="outline-btn" data-action="Exportar PDF">Exportar PDF</button></div><div class="search-row"><input class="search-box" placeholder="Buscar descrição, origem ou forma..."></div>${table(['Data','Descrição','Origem','Forma','Entrada','Saída','Saldo'],[])}</div></section>`,
  'Pontos de Venda': `
    <section class="page-shell"><div class="page-head"><div><h1>Pontos de venda</h1><p>Cadastre os locais e canais onde seus produtos são vendidos</p></div><button class="primary-btn" data-action="Novo ponto de venda">+ Novo ponto de venda</button></div>
    <div class="page-stats">${stat('orange','Canais cadastrados','3')}${stat('green','Canais com vendas','3')}${stat('yellow','Canal principal','Loja física')}</div>
    <div class="page-grid equal"><div class="panel"><h2>Pontos cadastrados</h2><input class="search-box" placeholder="Buscar ponto de venda..."><table class="data-table point-table"><thead><tr><th>Nome</th><th>Tipo</th><th>Status</th></tr></thead><tbody></tbody></table><div class="note-box"><strong>Integração com vendas</strong>Os pontos ativos aparecem automaticamente no formulário de nova venda e alimentam o gráfico “Vendas por canal”.</div></div><div class="panel"><h2>Dados do ponto de venda</h2><div class="form-grid">${field('Nome do ponto','Loja física')}${field('Tipo de canal','Presencial')}${field('Responsável','Vinicinho')}${field('Telefone / contato','')}${field('Endereço ou link','Rua, número ou endereço online','wide')}<div class="form-actions"><span class="active-chip">Ponto ativo</span><button class="primary-btn" data-action="Salvar ponto de venda">Salvar ponto</button></div></div></div></div></section>`,
  Relatórios: reportPage('financeiro'),
  Clientes: contactPage('cliente'),
  Fornecedores: contactPage('fornecedor')
};

function stat(color,label,value){return `<div class="stat-box"><i class="stat-color ${color}"></i><div><span>${label}</span><strong>${value}</strong></div></div>`}
function table(head,rows){return `<table class="data-table"><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function field(label,value,wide=''){return `<div class="form-group ${wide}"><label>${label}</label><input value="${value}"></div>`}
function contactPage(type){const client=type==='cliente';return `<section class="page-shell"><div class="page-head"><div><h1>Cadastro de ${client?'clientes':'fornecedores'}</h1><p>${client?'Organize contatos, endereços e histórico de compras':'Centralize contatos, produtos fornecidos e condições de compra'}</p></div><button class="primary-btn" data-action="Novo ${type}">+ Novo ${type}</button></div><div class="page-stats">${stat('orange',client?'Clientes ativos':'Fornecedores ativos','0')}${stat(client?'yellow':'red',client?'Com saldo pendente':'Compras no mês',client?'0':'R$ 0,00')}${stat(client?'red':'green',client?'Total a receber':'Contas a pagar','R$ 0,00')}</div><div class="page-grid equal"><div class="panel"><h2>${client?'Clientes':'Fornecedores'} cadastrados</h2><input class="search-box" placeholder="Buscar ${type}...">${table(client?['Cliente','Contato','Total comprado']:['Fornecedor','Compras no mês','A pagar','Status'],[])}<div class="note-box contact-summary"><strong>${client?'Histórico do cliente':'Resumo do fornecedor'}</strong><p>${client?'Compras realizadas':'Compras no mês'} <b style="float:right">—</b></p><p>${client?'Total comprado':'Contas a pagar'} <b style="float:right">R$ 0,00</b></p></div></div><div class="panel"><h2>Dados do ${type}</h2><div class="form-grid">${field(client?'Nome completo *':'Nome / Razão social *','')}${field('CPF/CNPJ','')}${field(client?'Telefone / WhatsApp *':'Contato principal','')}${field(client?'E-mail':'Telefone / WhatsApp *','')}${field('Endereço','')}${field(client?'Cidade / UF':'Categoria principal','')}${field(client?'Observações':'Produtos fornecidos','','wide')}<div class="form-actions"><span class="active-chip">Selecione um ${type}</span><button class="primary-btn" data-action="Salvar ${type}">Salvar alterações</button></div></div></div></div></section>`}
function reportTabs(active){return `<div class="report-tabs"><button class="${active==='financeiro'?'active':''}" data-report="financeiro">Financeiro</button><button class="${active==='vendas'?'active':''}" data-report="vendas">Vendas</button><button class="${active==='preVendas'?'active':''}" data-report="preVendas">Pré-vendas</button><button class="${active==='estoque'?'active':''}" data-report="estoque">Estoque atual</button><button class="${active==='despesasPeriodo'?'active':''}" data-report="despesasPeriodo">Despesas por período</button><button class="${active==='despesas'?'active':''}" data-report="despesas">Visão de despesas</button></div>`}
function periodFilter(){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10),end=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString().slice(0,10);return `<div class="report-period-filter"><label>Data inicial<input class="report-start" type="date" value="${start}"></label><label>Data final<input class="report-end" type="date" value="${end}"></label></div>`}
function salesReportPage(){return `<section class="page-shell"><div class="page-head"><div><h1>Relatório de vendas</h1><p>Consulte as vendas dentro do período escolhido</p></div><button class="outline-btn" data-action="Exportar PDF">Exportar PDF</button></div>${reportTabs('vendas')}${periodFilter()}<div class="page-stats four">${stat('orange','Total vendido','R$ 0,00')}${stat('green','Total recebido','R$ 0,00')}${stat('yellow','A receber','R$ 0,00')}${stat('deep','Quantidade de vendas','0')}</div><div class="panel report-data-panel"><h2>Vendas do período</h2>${table(['Data','Cliente','Produtos','Ponto de venda','Total','Recebido','Saldo'],[])}</div></section>`}
function stockReportPage(){return `<section class="page-shell"><div class="page-head"><div><h1>Relatório de estoque atual</h1><p>Posição atual de todos os produtos e ingredientes</p></div><button class="outline-btn" data-action="Exportar PDF">Exportar PDF</button></div>${reportTabs('estoque')}<div class="page-stats four">${stat('orange','Produtos cadastrados','0')}${stat('green','Unidades em estoque','0')}${stat('red','Custo do estoque','R$ 0,00')}${stat('deep','Valor potencial de venda','R$ 0,00')}</div><div class="panel report-data-panel"><h2>Posição do estoque</h2>${table(['Produto','Tipo','Estoque atual','Custo unitário','Custo total','Valor potencial'],[])}</div></section>`}
function expensePeriodReportPage(){return `<section class="page-shell"><div class="page-head"><div><h1>Relatório de despesas por período</h1><p>Consulte compras e contas dentro do período escolhido</p></div><button class="outline-btn" data-action="Exportar PDF">Exportar PDF</button></div>${reportTabs('despesasPeriodo')}${periodFilter()}<div class="page-stats four">${stat('red','Total das despesas','R$ 0,00')}${stat('green','Total pago','R$ 0,00')}${stat('yellow','Contas a pagar','R$ 0,00')}${stat('deep','Lançamentos','0')}</div><div class="panel report-data-panel"><h2>Despesas do período</h2>${table(['Data','Fornecedor','Categoria','Situação','Valor','Pago','A pagar'],[])}</div></section>`}
function preSalesReportPage(){const points=['Todos os pontos',...(window.vinicinhoSavedPoints||[])];return `<section class="page-shell"><div class="page-head"><div><h1>Relatório de pré-vendas</h1><p>Organize o pedido de compra por data e ponto de venda</p></div><button class="outline-btn" data-action="Exportar PDF">Exportar PDF</button></div>${reportTabs('preVendas')}<div class="report-period-filter"><label>Data inicial<input class="report-start" type="date"></label><label>Data final<input class="report-end" type="date"></label><label>Ponto de venda<select class="report-point">${points.map(point=>`<option>${point}</option>`).join('')}</select></label></div><div class="page-stats four">${stat('blue','Pré-vendas','0')}${stat('orange','Grupos','0')}${stat('deep','Unidades para comprar','0')}${stat('green','Total previsto','R$ 0,00')}</div><div class="page-grid presale-report-grid"><div class="panel report-data-panel"><h2>Grupos de pré-vendas</h2>${table(['Data','Ponto de venda','Pedidos','Clientes','Total'],[])}</div><div class="panel purchase-list-panel"><h2>Lista consolidada para compra</h2>${table(['Produto','Quantidade','Custo estimado'],[])}<div class="purchase-list-total"><span>Total de custo estimado</span><strong>R$ 0,00</strong></div></div></div></section>`}
function reportPage(mode){if(mode==='vendas')return salesReportPage();if(mode==='preVendas')return preSalesReportPage();if(mode==='estoque')return stockReportPage();if(mode==='despesasPeriodo')return expensePeriodReportPage();const finance=mode==='financeiro';return `<section class="page-shell"><div class="page-head"><div><h1>${finance?'Relatório financeiro':'Relatório de despesas'}</h1><p>${finance?'Vendas, gastos e lucro no mesmo lugar':'Analise gastos por período, fornecedor e categoria'}</p></div><button class="outline-btn" data-action="Exportar PDF">Exportar PDF</button></div>${reportTabs(finance?'financeiro':'despesas')}${finance?`<div class="page-stats four">${stat('orange','Vendas','R$ 32,00')}${stat('green','Recebido','R$ 10,00')}${stat('red','Despesas','R$ 8,00')}${stat('deep','Lucro previsto','R$ 24,00')}</div><div class="page-grid report"><div class="panel"><h2>Vendas × despesas × lucro</h2><div class="bar-chart"><div class="bar" style="height:75%;background:#f59a2c"><b>R$ 32,00</b><label>Vendas</label></div><div class="bar" style="height:24%;background:#30915d"><b>R$ 10,00</b><label>Recebido</label></div><div class="bar" style="height:19%;background:#ce4b3b"><b>R$ 8,00</b><label>Despesas</label></div><div class="bar" style="height:56%"><b>R$ 24,00</b><label>Lucro</label></div></div></div><div class="side-stack"><div class="panel"><h2>Resultado do período</h2><div class="result-line"><span>Vendas brutas</span><b>R$ 32,00</b></div><div class="result-line"><span>(-) Despesas</span><b class="red-text">R$ 8,00</b></div><div class="result-line"><span>(=) Lucro previsto</span><b class="green-text">R$ 24,00</b></div></div><div class="panel"><h2>Observações</h2><div class="mini-list"><div><span>Recebido agora</span><b class="green-text">R$ 10,00</b></div><div class="mini-list"><span>A receber</span><b class="orange-text">R$ 22,00</b></div></div><div class="note-box" style="margin-top:18px">O lucro previsto considera também os valores ainda não recebidos.</div></div></div></div>`:`<div class="page-stats">${stat('red','Total gasto','R$ 8,00')}${stat('deep','Maior categoria','Ingredientes')}${stat('orange','Fornecedor principal','Mercado Central')}</div><div class="page-grid report"><div class="panel"><h2>Evolução das despesas</h2><p>Gastos diários — Agosto/2026</p><div class="bar-chart">${[12,20,29,16,38,25,47].map((h,i)=>`<div class="bar" style="height:${h}%"><label>${i+13}</label></div>`).join('')}</div></div><div class="side-stack"><div class="panel"><h2>Por categoria</h2><div class="donut-big"><b>R$ 8</b></div><p style="text-align:center"><b>Ingredientes</b> &nbsp; <b class="orange-text">100%</b></p></div><div class="panel"><h2>Detalhamento</h2>${table(['Fornecedor','Categoria','Valor'],[['<b>Mercado Central</b>','Ingredientes','<b class="red-text">R$ 8,00</b>']])}</div></div></div>`}</section>`}
