(function(){
  const firebaseConfig={apiKey:'AIzaSyBY35RmjCQcfGc0Kj3LZll5J2jHaHooW24',authDomain:'vinicinho-doces-vf70.firebaseapp.com',projectId:'vinicinho-doces-vf70',storageBucket:'vinicinho-doces-vf70.firebasestorage.app',messagingSenderId:'697137577803',appId:'1:697137577803:web:f748d80d4b699a6e98f2ce'};
  firebase.initializeApp(firebaseConfig);
  const db=firebase.firestore(),serverTimestamp=firebase.firestore.FieldValue.serverTimestamp,arrayUnion=firebase.firestore.FieldValue.arrayUnion;
  const groups=[{name:'Cones Trufados',icon:'🍦'},{name:'Pão de Mel',icon:'🍯'},{name:'Bala de Ninho',icon:'🍬'},{name:'Bolos de pote',icon:'🍰'}];
  const state={customer:null,products:[],cart:{},orders:[],activeGroup:'',ordersUnsubscribe:null};
  const $=selector=>document.querySelector(selector),money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const escape=value=>{const element=document.createElement('div');element.textContent=String(value||'');return element.innerHTML};
  function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2600)}
  function phoneDigits(value){return String(value||'').replace(/\D/g,'')}
  async function digest(value){const data=new TextEncoder().encode(value),hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,'0')).join('').slice(0,32)}
  function saveSession(){localStorage.setItem('vinicinho-store-session',JSON.stringify(state.customer))}
  function setEntryMessage(message){$('#entryMessage').textContent=message}
  async function register(name,phone){const digits=phoneDigits(phone);if(digits.length<10)throw Error('Digite um telefone válido com DDD.');const key=await digest(`phone:${digits}`),profile={key,name:name.trim(),phone:digits,registered:true,updatedAt:serverTimestamp()};await db.collection('storefrontCustomers').doc(key).set(profile,{merge:true});state.customer={key,name:name.trim(),phone:digits,registered:true};saveSession();startStore()}
  async function login(phone){const digits=phoneDigits(phone);if(digits.length<10)throw Error('Digite um telefone válido com DDD.');const key=await digest(`phone:${digits}`),snapshot=await db.collection('storefrontCustomers').doc(key).get();if(!snapshot.exists)throw Error('Telefone ainda não cadastrado. Use Primeiro acesso.');const profile=snapshot.data();state.customer={key,name:profile.name||'Cliente',phone:digits,registered:true};saveSession();startStore()}
  async function continueGuest(name){const clean=name.trim();if(!clean)throw Error('Digite seu nome.');let key=localStorage.getItem('vinicinho-guest-key');if(!key){key=`guest-${crypto.randomUUID()}`;localStorage.setItem('vinicinho-guest-key',key)}state.customer={key,name:clean,phone:'',registered:false};saveSession();startStore()}
  function startStore(){
    $('#entryScreen').classList.add('hidden');$('#storeScreen').classList.remove('hidden');$('#customerName').textContent=state.customer.name;
    db.collection('storefront').doc('catalog').onSnapshot(snapshot=>{state.products=(snapshot.data()?.products||[]).filter(product=>product.group);renderGroups();renderProducts()});
    state.ordersUnsubscribe?.();state.ordersUnsubscribe=db.collection('storefrontCustomers').doc(state.customer.key).collection('orders').orderBy('createdAt','desc').onSnapshot(snapshot=>{state.orders=snapshot.docs.map(doc=>({id:doc.id,...doc.data()}));renderOrders();updateNotifications()});
  }
  function renderGroups(){
    $('#groupGrid').innerHTML=groups.map(group=>{const count=state.products.filter(product=>product.group===group.name).length;return `<button class="group-card ${state.activeGroup===group.name?'active':''}" data-group="${escape(group.name)}"><span>${group.icon}</span><b>${escape(group.name)}</b><small>${count} ${count===1?'opção':'opções'}</small></button>`}).join('');
    document.querySelectorAll('[data-group]').forEach(button=>button.onclick=()=>{state.activeGroup=button.dataset.group;renderGroups();renderProducts();$('#productsSection').scrollIntoView({behavior:'smooth'})});
  }
  function renderProducts(){
    const products=state.products.filter(product=>!state.activeGroup||product.group===state.activeGroup);$('#productsTitle').textContent=state.activeGroup||'Todos os produtos';$('#emptyProducts').classList.toggle('hidden',products.length>0);
    $('#productGrid').innerHTML=products.map(product=>`<article class="product-card"><span class="product-emoji">${escape(product.emoji||'🍬')}</span><div><h3>${escape(product.name)}</h3><p>${escape(product.description||product.group)}</p><strong>${money(product.price)}</strong><span class="stock-label ${product.stock>0?'':'out'}">${product.stock>0?`${product.stock} un. para entrega`:'Disponível por encomenda'}</span></div><button class="add-product" data-add="${escape(product.id)}" aria-label="Adicionar ${escape(product.name)}">+</button></article>`).join('');
    document.querySelectorAll('[data-add]').forEach(button=>button.onclick=()=>addToCart(button.dataset.add));
  }
  function addToCart(id){state.cart[id]=(state.cart[id]||0)+1;updateCart();toast('Produto adicionado ao carrinho')}
  function updateCart(){const count=Object.values(state.cart).reduce((sum,value)=>sum+value,0);$('#cartCount').textContent=count;renderCart()}
  function cartEntries(){return Object.entries(state.cart).map(([id,quantity])=>({product:state.products.find(product=>product.id===id),quantity})).filter(item=>item.product&&item.quantity>0)}
  function renderCart(){const entries=cartEntries();$('#cartItems').innerHTML=entries.length?entries.map(({product,quantity})=>`<div class="cart-line"><div><b>${escape(product.name)}</b><small>${money(product.price)} cada</small></div><div class="quantity-control"><button data-minus="${escape(product.id)}">−</button><b>${quantity}</b><button data-plus="${escape(product.id)}">+</button></div><button class="remove-cart" data-remove="${escape(product.id)}">Remover</button></div>`).join(''):'<p>Seu carrinho está vazio.</p>';$('#cartTotal').textContent=money(entries.reduce((sum,item)=>sum+item.product.price*item.quantity,0));$('#checkoutButton').disabled=!entries.length;document.querySelectorAll('[data-minus]').forEach(button=>button.onclick=()=>changeQuantity(button.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(button=>button.onclick=()=>changeQuantity(button.dataset.plus,1));document.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{delete state.cart[button.dataset.remove];updateCart()})}
  function changeQuantity(id,amount){state.cart[id]=Math.max(0,(state.cart[id]||0)+amount);if(!state.cart[id])delete state.cart[id];updateCart()}
  function openModal(id){document.getElementById(id).classList.remove('hidden')}
  function closeModal(id){document.getElementById(id).classList.add('hidden')}
  function prepareCheckout(){const entries=cartEntries(),canDeliver=entries.every(item=>item.product.stock>=item.quantity);$('#deliveryOption').classList.toggle('disabled',!canDeliver);$('#deliveryOption input').disabled=!canDeliver;$('#checkoutWarning').textContent=canDeliver?'':'Alguns itens não estão em estoque. Este pedido precisa ser feito como encomenda.';document.querySelector('input[name="fulfillment"][value="encomenda"]').checked=true;toggleFulfillment();const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);$('#deliveryDate').min=tomorrow.toISOString().slice(0,10);$('#deliveryDate').value=tomorrow.toISOString().slice(0,10);closeModal('cartModal');openModal('checkoutModal')}
  function toggleFulfillment(){const type=document.querySelector('input[name="fulfillment"]:checked').value;$('#dateField').classList.toggle('hidden',type!=='encomenda');$('#addressField').classList.toggle('hidden',type!=='entrega')}
  async function placeOrder(){
    const entries=cartEntries();if(!entries.length)return;const fulfillment=document.querySelector('input[name="fulfillment"]:checked').value,deliveryDate=$('#deliveryDate').value,address=$('#deliveryAddress').value.trim(),paymentMethod=$('#paymentMethod').value;if(fulfillment==='encomenda'&&!deliveryDate)return toast('Escolha a data da encomenda.');if(fulfillment==='entrega'&&!address)return toast('Informe o local de entrega.');
    const items=entries.map(({product,quantity})=>({id:product.id,name:product.name,quantity,price:product.price,stockAtOrder:product.stock,group:product.group})),total=items.reduce((sum,item)=>sum+item.price*item.quantity,0),order={customerKey:state.customer.key,customerName:state.customer.name,customerPhone:state.customer.phone||'',registered:state.customer.registered,items,total,fulfillment,deliveryDate:fulfillment==='encomenda'?deliveryDate:'',address:fulfillment==='entrega'?address:'',paymentMethod,status:'novo',messages:[{sender:'customer',text:'Pedido enviado. Aguardo a confirmação.',createdAt:new Date().toISOString()}],adminUnread:true,customerUnread:false,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};
    const button=$('#placeOrderButton');button.disabled=true;try{await db.collection('storefrontCustomers').doc(state.customer.key).collection('orders').add(order);state.cart={};updateCart();closeModal('checkoutModal');toast('Pedido enviado para o Vinicinho!');setTimeout(()=>openModal('ordersModal'),500)}catch(error){console.error(error);toast('Não foi possível enviar. Tente novamente.')}finally{button.disabled=false}
  }
  function statusLabel(status){return ({novo:'Aguardando resposta',aceito:'Aceito',recusado:'Recusado',preparando:'Em preparo',pronto:'Pronto',finalizado:'Finalizado',pre_venda:'Encomenda aceita'})[status]||status}
  function orderDate(order){const date=order.createdAt?.toDate?.()||new Date();return date.toLocaleString('pt-BR')}
  function renderOrders(){$('#ordersList').innerHTML=state.orders.length?state.orders.map(order=>`<button class="order-card" data-order="${order.id}"><header><b>Pedido • ${money(order.total)}</b><span class="status ${escape(order.status)}">${statusLabel(order.status)}</span></header><small>${orderDate(order)} • ${order.fulfillment==='entrega'?'Entrega':'Encomenda'}</small><p>${order.items?.map(item=>`${item.quantity}× ${escape(item.name)}`).join(', ')}</p></button>`).join(''):'<p>Você ainda não fez nenhum pedido.</p>';document.querySelectorAll('[data-order]').forEach(button=>button.onclick=()=>openOrderDetail(state.orders.find(order=>order.id===button.dataset.order)))}
  function updateNotifications(){const count=state.orders.filter(order=>order.customerUnread).length;$('#notificationCount').textContent=count;$('#notificationCount').style.display=count?'block':'none'}
  async function openOrderDetail(order){if(!order)return;const messages=(order.messages||[]).map(message=>`<div class="chat-message ${message.sender==='customer'?'customer':'admin'}"><b>${message.sender==='customer'?'Você':'Vinicinho Doces'}</b><p>${escape(message.text)}</p><small>${new Date(message.createdAt||Date.now()).toLocaleString('pt-BR')}</small></div>`).join('');$('#orderDetail').innerHTML=`<div class="order-detail-head"><div><small>Pedido de ${orderDate(order)}</small><h2>${statusLabel(order.status)}</h2></div><span class="status ${escape(order.status)}">${money(order.total)}</span></div><div class="order-items">${(order.items||[]).map(item=>`<div><span>${item.quantity}× ${escape(item.name)}</span><b>${money(item.price*item.quantity)}</b></div>`).join('')}</div><p><b>${order.fulfillment==='entrega'?'Local de entrega':'Data da encomenda'}:</b> ${escape(order.fulfillment==='entrega'?order.address:new Date(order.deliveryDate+'T12:00:00').toLocaleDateString('pt-BR'))}</p><section class="chat-box"><h3>Conversa com Vinicinho</h3><div class="chat-messages">${messages}</div><div class="chat-compose"><input placeholder="Digite uma mensagem"><button>Enviar</button></div></section>`;closeModal('ordersModal');openModal('orderDetailModal');if(order.customerUnread)await db.collection('storefrontCustomers').doc(state.customer.key).collection('orders').doc(order.id).update({customerUnread:false,updatedAt:serverTimestamp()});const input=$('#orderDetail .chat-compose input'),button=$('#orderDetail .chat-compose button');button.onclick=async()=>{const text=input.value.trim();if(!text)return;button.disabled=true;await db.collection('storefrontCustomers').doc(state.customer.key).collection('orders').doc(order.id).update({messages:arrayUnion({sender:'customer',text,createdAt:new Date().toISOString()}),adminUnread:true,customerUnread:false,updatedAt:serverTimestamp()});input.value='';button.disabled=false;toast('Mensagem enviada')}}
  document.querySelectorAll('[data-entry-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-entry-tab]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.entry-form').forEach(form=>form.classList.toggle('active',form.id===(button.dataset.entryTab==='register'?'registerForm':'loginForm')));setEntryMessage('')});
  $('#registerForm').onsubmit=async event=>{event.preventDefault();setEntryMessage('');try{const data=new FormData(event.currentTarget);await register(data.get('name'),data.get('phone'))}catch(error){setEntryMessage(error.message)}};
  $('#loginForm').onsubmit=async event=>{event.preventDefault();setEntryMessage('');try{const data=new FormData(event.currentTarget);await login(data.get('phone'))}catch(error){setEntryMessage(error.message)}};
  $('#guestForm').onsubmit=async event=>{event.preventDefault();setEntryMessage('');try{await continueGuest(new FormData(event.currentTarget).get('name'))}catch(error){setEntryMessage(error.message)}};
  $('#showAllButton').onclick=()=>{state.activeGroup='';renderGroups();renderProducts()};$('#cartButton').onclick=()=>{renderCart();openModal('cartModal')};$('#ordersButton').onclick=()=>openModal('ordersModal');$('#checkoutButton').onclick=prepareCheckout;$('#placeOrderButton').onclick=placeOrder;document.querySelectorAll('input[name="fulfillment"]').forEach(input=>input.onchange=toggleFulfillment);document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>closeModal(button.dataset.close));document.querySelectorAll('.backdrop').forEach(backdrop=>backdrop.onclick=event=>{if(event.target===backdrop)closeModal(backdrop.id)});$('#logoutButton').onclick=()=>{localStorage.removeItem('vinicinho-store-session');location.reload()};
  const session=JSON.parse(localStorage.getItem('vinicinho-store-session')||'null');if(session?.key&&session?.name){state.customer=session;startStore()}
})();
